# Generated by Django 4.2.7 on 2025-11-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ForumPostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_platform', models.CharField(blank=True, help_text='Platform where shared (optional)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.forumpost')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_shares', to='core.chatsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ForumPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.forumpost')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_likes', to='core.chatsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('post', 'session')},
            },
        ),
    ]
